server:
    port: 9080
    
spring:
    datasource:
        url: jdbc:postgresql://119.23.241.12:5432/kuhyygy
        username: chenjw
        password: helloumcc
        driver-class-name: org.postgresql.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            initial-size: 8
            min-idle: 1
            max-active: 20
            max-wait: 60000
            time-between-eviction-runsMillis: 60000
            min-evictable-idle-timeMillis: 300000
            validation-query: select version()
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-open-prepared-statements: 20
            max-pool-prepared-statement-per-connection-size: 20
            filters: stat
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            use-global-data-source-stat: true

mybatis:
    type-aliases-package: com.chenx.chenbasic.pojo
    #指定sql映射文件的位置
    mapper-locations: classpath:mapper/*.xml  
    configuration:
        default-fetch-size: 100
        default-statement-timeout: 30

pagehelper:
    helperDialect: postgresql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check